### ISSUE TITLE
Test checklist

### ISSUE THREAD

**Issue by garyb** [purescript-deprecated/core-tests#1]
- [ ] prelude
- [x] [arrays](https://github.com/purescript/purescript-arrays)
- [ ] [control](https://github.com/purescript/purescript-control)
- [x] [either](https://github.com/purescript/purescript-either)
- [x] [enums](https://github.com/purescript/purescript-enums)
- [ ] [exceptions](https://github.com/purescript/purescript-exceptions)
- [ ] [foldable-traversable](https://github.com/purescript/purescript-foldable-traversable)
- [ ] [foreign](https://github.com/purescript/purescript-foreign)
- [x] [globals](https://github.com/purescript/purescript-globals)
- [x] [math](https://github.com/purescript/purescript-math)
- [x] [maybe](https://github.com/purescript/purescript-maybe)
- [ ] [monoid](https://github.com/purescript/purescript-monoid)
- [ ] [random](https://github.com/purescript/purescript-random)
- [ ] [refs](https://github.com/purescript/purescript-refs)
- [x] [strings](https://github.com/purescript/purescript-strings)
- [x] [tuples](https://github.com/purescript/purescript-tuples)
- [ ] [validation](https://github.com/purescript/purescript-validation)
